export const fakeVendor = [
  {
    // name: "Phong Vu",
    // type: "Computer",
    // totalSpend: 1000,
    // status: "active",
    // countryOfRegistration: "Vietnam",
    // companyRegistrationNumber: "84",
    // qualified: "Good",
    // companyWebsite: "haha.com",
    // internalRepresentative: "unknown",
    // relationshipSince: "2020",
    // currentContact: "Myself",
    // mainContactPerson: "Nguyen Viet Duc",
    // officialEmail: "pv@gmail.com",
    // secondaryEmail: "pv1@gmail.com",
    // mobileNumber: "0938155774",

    name: "FPT",
    type: "vendor",
    totalSpend: 2500,
    status: "active",
    countryOfRegistration: "Vietnam",
    companyRegistrationNumber: "84",
    qualified: "Yes",
    companyWebsite: "haha.com",
    internalRepresentative: "unknown",
    relationshipSince: "2020",
    currentContact: "CNTR_1",
    mainContactPerson: "Tuan",
    officialEmail: "fpt@gmail.com",
    secondaryEmail: "1@gmail.com",
    mobileNumber: "0938 115 555",
  },

  {
    // name: "ABC",
    // type: "Computer",
    // totalSpend: 1000,
    // status: "active",
    // countryOfRegistration: "USA",
    // companyRegistrationNumber: "1",
    // qualified: "preeminent",
    // companyWebsite: "haha.com",
    // internalRepresentative: "unknown",
    // relationshipSince: "2020",
    // currentContact: "Boo",
    // mainContactPerson: "Le Tuan",
    // officialEmail: "lt@gmail.com",
    // secondaryEmail: "lt1@gmail.com",
    // mobileNumber: "0958411284",

    name: "CNPM",
    type: "vendor",
    totalSpend: 1000,
    status: "active",
    countryOfRegistration: "Vietnam",
    companyRegistrationNumber: "84",
    qualified: "Yes",
    companyWebsite: "haha.com",
    internalRepresentative: "unknown",
    relationshipSince: "2020",
    currentContact: "TNRR_2",
    mainContactPerson: "Minh",
    officialEmail: "cnpm@gmail.com",
    secondaryEmail: "2@gmail.com",
    mobileNumber: "0938 115 194",
  },
];

export const fakeContract = [
  {
    // contractNumber: "CNTR_1",
    // contractMemberCorrect: "Le Vu",
    // product: "Computer",
    // contractTitle: "Hop dong cung cap vat tu",
    // contract: "New",
    // vendor: "Phong Vu",
    // type: "Lease",
    // editDate: "29/01/2020",
    // editContent: "contract",
    // history: "15",

    contractNumber: "CNTR_1",
    contractMemberCorrect: "CNTR_1",
    product: "Computer",
    contractTitle: "Hợp đồng cung cấp vật tư",
    contract: "Hợp đồng cung cấp vật tư",
    vendor: "Gear",
    type: "sale",
    startDate: "2/01/2020",
    endDate: "2/12/2020",
    editDate: "29/01/2020",
    editContent: "contract",
    history: "15",
  },
  {
  
    // contractNumber: "CNTR_2",
    // contractMemberCorrect: "Vu Phong",
    // product: "Computer",
    // contractTitle: "Hop dong cung cap vat tu",
    // contract: "New",
    // vendor: "ABC",
    // type: "Lease",
    // editDate: "28/02/2020",
    // editContent: "contractMemberCorrect",

    contractNumber: "4",
    contractMemberCorrect: "CNTR_2",
    product: "Computer",
    contractTitle: "Hợp đồng cung cấp vật tư",
    contract: "Hợp đồng cung cấp vật tư",
    vendor: "Phong Vu",
    type: "lease",
    editDate: "28/02/2020",
    editContent: "contractMemberCorrect",
    history: "15",
    
  },
];

export const fakeRecommendVendor = [
  {
    // name: "Park",
    // type: "vendor",
    // totalSpend: 1000,
    // status: "active",
    // countryOfRegistration: "Vietnam",
    // companyRegistrationNumber: "84",
    // qualified: "good",
    // companyWebsite: "haha.com",
    // internalRepresentative: "unknown",
    // relationshipSince: "2020",
    // currentContact: "Myself",
    // mainContactPerson: "Myself",
    // officialEmail: "a@gmail.com",
    // secondaryEmail: "1@gmail.com",
    // mobileNumber: "123456789",

    name: "Phong Vu",
    type: "vendor",
    totalSpend: 1000,
    status: "active",
    countryOfRegistration: "Vietnam",
    companyRegistrationNumber: "84",
    qualified: "good",
    companyWebsite: "phongvu.com",
    internalRepresentative: "unknown",
    relationshipSince: "2020",
    product: "Computer",
    mainContactPerson: "Minh",
    officialEmail: "pb@gmail.com",
    secondaryEmail: "1@gmail.com",
    mobileNumber: "123456789",
  },

  {
    // name: "Pleez",
    // type: "vendor",
    // totalSpend: 1000,
    // status: "active",
    // countryOfRegistration: "Vietnam",
    // companyRegistrationNumber: "84",
    // qualified: "pretty good",
    // companyWebsite: "haha.com",
    // internalRepresentative: "unknown",
    // relationshipSince: "2020",
    // currentContact: "Boo",
    // mainContactPerson: "Boom",
    // officialEmail: "b@gmail.com",
    // secondaryEmail: "2@gmail.com",
    // mobileNumber: "123456789",

    name: "Gear Vn",
    type: "vendor",
    totalSpend: 1000,
    status: "active",
    countryOfRegistration: "Vietnam",
    companyRegistrationNumber: "84",
    qualified: "pretty good",
    companyWebsite: "gearvn.com",
    internalRepresentative: "unknown",
    relationshipSince: "2020",
    product: "Computer",
    mainContactPerson: "Dat",
    officialEmail: "gearvn@gmail.com",
    secondaryEmail: "2@gmail.com",
    mobileNumber: "123456789",
  },

  {
    name: "ABC",
    type: "vendor",
    totalSpend: 1000,
    status: "active",
    countryOfRegistration: "Vietnam",
    companyRegistrationNumber: "84",
    qualified: "pretty good",
    companyWebsite: "haha.com",
    internalRepresentative: "unknown",
    relationshipSince: "2020",
    currentContact: "ABC_contract",
    mainContactPerson: "Tuan",
    officialEmail: "b@gmail.com",
    secondaryEmail: "abc@gmail.com",
    mobileNumber: "123456789",
  },
];

export const fakeRateVendor = [
  // {
  //   vendor: "hehe",
  //   type: "vendor",
  //   totalSpend: 1000,
  //   status: "active",
  //   countryOfRegistration: "Vietnam",
  //   companyRegistrationNumber: "84",
  //   qualified: "Yes",
  //   companyWebsite: "haha.com",
  //   internalRepresentative: "unknown",
  //   relationshipSince: "2020",
  //   currentContact: "Myself",
  //   mainContactPerson: "Myself",
  //   officialEmail: "a@gmail.com",
  //   secondaryEmail: "1@gmail.com",
  //   mobileNumber: "123456789",
  // },
  // {
  //   vendor: "hoho",
  //   type: "vendor",
  //   totalSpend: 1000,
  //   status: "active",
  //   countryOfRegistration: "Vietnam",
  //   companyRegistrationNumber: "84",
  //   qualified: "Yes",
  //   companyWebsite: "haha.com",
  //   internalRepresentative: "unknown",
  //   relationshipSince: "2020",
  //   currentContact: "Boo",
  //   mainContactPerson: "Boom",
  //   officialEmail: "b@gmail.com",
  //   secondaryEmail: "2@gmail.com",
  //   mobileNumber: "123456789",
  // },
];
