export const fakeVendor = [
  {
    name: "1",
    type: "vendor",
    totalSpend: 1000,
    status: "active",
    countryOfRegistration: "Vietnam",
    companyRegistrationNumber: "84",
    qualified: "Yes",
    companyWebsite: "haha.com",
    internalRepresentative: "unknown",
    relationshipSince: "2020",
    currentContact: "Myself",
    mainContactPerson: "Myself",
    officialEmail: "a@gmail.com",
    secondaryEmail: "1@gmail.com",
    mobileNumber: "123456789",
  },

  {
    name: "2",
    type: "vendor",
    totalSpend: 1000,
    status: "active",
    countryOfRegistration: "Vietnam",
    companyRegistrationNumber: "84",
    qualified: "Yes",
    companyWebsite: "haha.com",
    internalRepresentative: "unknown",
    relationshipSince: "2020",
    currentContact: "Boo",
    mainContactPerson: "Boom",
    officialEmail: "b@gmail.com",
    secondaryEmail: "2@gmail.com",
    mobileNumber: "123456789",
  },
];

export const fakeContract = [
  {
    fakeContract:"hello",
    contractNumber: "3",
    contractMemberCorrect: "what",
    product: "hummm",
    contractTitle: "Guess what",
    contract: "huh",
    vendor: "me",
    type: "ohh",
    editDate: "29/01/2020",
    editContent: "contract",
    history: "15",
  },
  {
    contractTitle: "Heello",
    contractNumber: "4",
    contractMemberCorrect: "wwhuttt",
    product: "haaaaa",
    contractTitle: "That's right",
    contract: "huh",
    vendor: "me",
    type: "ohh",
    editDate: "28/02/2020",
    editContent: "contractMemberCorrect",
    
  },
];

export const fakeRecommendVendor = [
  {
    name: "Park",
    type: "vendor",
    totalSpend: 1000,
    status: "active",
    countryOfRegistration: "Vietnam",
    companyRegistrationNumber: "84",
    qualified: "good",
    companyWebsite: "haha.com",
    internalRepresentative: "unknown",
    relationshipSince: "2020",
    currentContact: "Myself",
    mainContactPerson: "Myself",
    officialEmail: "a@gmail.com",
    secondaryEmail: "1@gmail.com",
    mobileNumber: "123456789",
  },

  {
    name: "Pleez",
    type: "vendor",
    totalSpend: 1000,
    status: "active",
    countryOfRegistration: "Vietnam",
    companyRegistrationNumber: "84",
    qualified: "pretty good",
    companyWebsite: "haha.com",
    internalRepresentative: "unknown",
    relationshipSince: "2020",
    currentContact: "Boo",
    mainContactPerson: "Boom",
    officialEmail: "b@gmail.com",
    secondaryEmail: "2@gmail.com",
    mobileNumber: "123456789",
  },
];

export const fakeRateVendor = [
  // {
  //   vendor: "hehe",
  //   type: "vendor",
  //   totalSpend: 1000,
  //   status: "active",
  //   countryOfRegistration: "Vietnam",
  //   companyRegistrationNumber: "84",
  //   qualified: "Yes",
  //   companyWebsite: "haha.com",
  //   internalRepresentative: "unknown",
  //   relationshipSince: "2020",
  //   currentContact: "Myself",
  //   mainContactPerson: "Myself",
  //   officialEmail: "a@gmail.com",
  //   secondaryEmail: "1@gmail.com",
  //   mobileNumber: "123456789",
  // },
  // {
  //   vendor: "hoho",
  //   type: "vendor",
  //   totalSpend: 1000,
  //   status: "active",
  //   countryOfRegistration: "Vietnam",
  //   companyRegistrationNumber: "84",
  //   qualified: "Yes",
  //   companyWebsite: "haha.com",
  //   internalRepresentative: "unknown",
  //   relationshipSince: "2020",
  //   currentContact: "Boo",
  //   mainContactPerson: "Boom",
  //   officialEmail: "b@gmail.com",
  //   secondaryEmail: "2@gmail.com",
  //   mobileNumber: "123456789",
  // },
];
